src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Annotations\Input;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\TeamRepository;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 */
#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team extends Entity
{
    /**
	 * @Input(groupBy="league")
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    /**
	 * @Input
     * @Assert\Expression(
     *     "this.getLeague().hasTeam(this) || this.getLeague().getParties().count() == 0",
     *     message="Die Liga läuft bereits!"
     * )
     * @Assert\Expression(
     *     "this.getLeague().hasTeam(this) || this.getLeague().getMaximumTeams() > this.getLeague().getTeams().count()",
     *     message="Die Liga ist bereits voll!"
     * )
     * @ORM\ManyToOne(targetEntity="App\Entity\League", inversedBy="teams")
     * @ORM\JoinColumn(nullable=false)
     */
    #[ORM\ManyToOne(targetEntity:'App\Entity\League', inversedBy:'teams')]
    #[ORM\JoinColumn(nullable:false)]
    private $league;

    /**
	 * @Input
     * @ORM\Column(type="string", length=255)
     */
    #[ORM\Column(type:"string")]
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Member", mappedBy="team", orphanRemoval=true)
     */
    #[ORM\OneToMany(targetEntity:"App\Entity\Member", mappedBy:"team", orphanRemoval:true)]
    private $members;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Party", mappedBy="team", cascade={"persist","remove"}, orphanRemoval=true)
     */
    #[ORM\OneToMany(targetEntity:"App\Entity\Party", mappedBy:"team", cascade:["persist","remove"], orphanRemoval:true)]
    private $homeParties;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Party", mappedBy="opponent", cascade={"persist","remove"}, orphanRemoval=true)
     */
    #[ORM\OneToMany(targetEntity:"App\Entity\Party", mappedBy:"opponent", cascade:["persist","remove"], orphanRemoval:true)]
    private $guestParties;
	
	
    public function __construct()
    {
        $this->homeParties = new ArrayCollection();
        $this->guestParties = new ArrayCollection();
        $this->members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLeague(): ?League
    {
        return $this->league;
    }

    public function setLeague(?League $league): self
    {
        $this->league = $league;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Member[]
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Member $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            $member->setTeam($this);
        }

        return $this;
    }

    public function removeMember(Member $member): self
    {
        if ($this->members->contains($member)) {
            $this->members->removeElement($member);
            // set the owning side to null (unless already changed)
            if ($member->getTeam() === $this) {
                $member->setTeam(null);
            }
        }

        return $this;
    }
	
    /**
     * @return Collection|Party[]
     */
    public function getHomeParties(): Collection
    {
        return $this->homeParties;
    }

    public function addHomeParty(Party $homeParty): self
    {
        if (!$this->homeParties->contains($homeParty)) {
            $this->homeParties[] = $homeParty;
            $homeParty->setTeam($this);
        }

        return $this;
    }

    public function removeHomeParty(Party $homeParty): self
    {
        if ($this->homeParties->contains($homeParty)) {
            $this->homeParties->removeElement($homeParty);
            // set the owning side to null (unless already changed)
            if ($homeParty->getTeam() === $this) {
                $homeParty->setTeam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Party[]
     */
    public function getGuestParties(): Collection
    {
        return $this->guestParties;
    }
	
    public function addGuestParty(Party $guestParty): self
    {
        if (!$this->guestParties->contains($guestParty)) {
            $this->guestParties[] = $guestParty;
            $guestParty->setOpponent($this);
        }

        return $this;
    }

    public function removeGuestParty(Party $guestParty): self
    {
        if ($this->guestParties->contains($guestParty)) {
            $this->guestParties->removeElement($guestParty);
            if ($guestParty->getOpponent() === $this) {
                $guestParty->setOpponent(null);
            }
        }
        return $this;
    }
	
	public function getParties() {
		$parties = [];
		foreach($this->getHomeParties() as $match) {
			$parties[$match->getId()] = $match;
		}
		foreach($this->getGuestParties() as $match) {
			$parties[$match->getId()] = $match;
		}
		return new ArrayCollection(array_values($parties));
	}
	
	public function getWins() {
		$parties = new ArrayCollection();
		foreach($this->getHomeParties() as $match) {
			if ($match->getScore()>$match->getOpponentScore()) {
				$parties->add($match);
			}
		}
		foreach($this->getGuestParties() as $match) {
			if ($match->getScore()<$match->getOpponentScore()) {
				$parties->add($match);
			}
		}
		return $parties;
	}
	public function getDraws() {
		$parties = new ArrayCollection();
		foreach($this->getParties() as $match) {
			if ($match->getScore()==$match->getOpponentScore()) {
				$parties->add($match);
			}
		}
		return $parties;
	}
	public function getLosses() {
		$parties = new ArrayCollection();
		foreach($this->getHomeParties() as $match) {
			if ($match->getScore()<$match->getOpponentScore()) {
				$parties->add($match);
			}
		}
		foreach($this->getGuestParties() as $match) {
			if ($match->getScore()>$match->getOpponentScore()) {
				$parties->add($match);
			}
		}
		return $parties;
	}
	public function getGoals() {
		$goals = 0;
		foreach($this->getHomeParties() as $match) {
			$goals += $match->getScore();
		}
		foreach($this->getGuestParties() as $match) {
			$goals += $match->getOpponentScore();
		}
		return $goals;
	}
	public function getOpponentGoals() {
		$goals = 0;
		foreach($this->getHomeParties() as $match) {
			$goals += $match->getOpponentScore();
		}
		foreach($this->getGuestParties() as $match) {
			$goals += $match->getScore();
		}
		return $goals;
	}
	public function getScore() {
		$score = count($this->getWins()) * 3;
		$score += count($this->getDraws());
		return $score;
	}
	public function isMyTurn() {
		foreach($this->league->getTeams() as $team) {
			if (count($team->getParties())<count($this->getParties())) {
				return false;
			}
		}
		return true;
	}
	public function __ToString() {
		return $this->getName();
		}
}

templates/base.html copy.twig
<!DOCTYPE html>
<html lang="de" style="height:100%;">
    <head>
    
        <meta charset="UTF-8" /> 
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        {% block css %}{% endblock %}
    </head>
    <body class="bg-dark" style="height:100%;">
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html lang="de" style="height:100%;">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <style>   
	#page-container {
		height:100%;
	}
    .page-footer>li { width:100%;}
    .page-footer {
bottom: 0px;
width: 100%;
    }
    body {overflow-x: hidden;} 
    </style>
    <body style="height:100%;">
        {% block body %}{% endblock %}
    </body>
</html>

templates/entity.html.twig
{% extends 'layout.html.twig' %}
{% block content_header %}{{entity}} administration{% endblock %}
{% block content_body %}
	{{ form(selectEntityForm) }}
{{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_widget(form) }}
	<div class="form-group row">
	<div class="col text-center">
	<button class="btn btn-outline-primary  btn-lg ml-3" type="submit">save <i class="fa fa-sm fa-save"></i> </button>
	{% if id!=null %}
	
	<a class="btn btn-outline-danger btn-lg  ml-3" href="{{path('remove_entity',{entity:entity,id:id})}}" role="button" onclick="return confirm('Are you sure?');" > remove <i class="fa fa-sm fa-trash"></i></a>
	{% endif %}
	</div>
    </div>

{{ form_end(form) }}
{% endblock %}
{% block content_footer %}{% endblock %}
{% block jquery %}
	{{ parent() }}
	$('.entitySelector').on('change', function() {
		if ($(this).val()=='') {
			window.location = '{{ path('add_entity', {entity: entity}) }}';
		} else {
			window.location = '{{ path('edit_entity', {entity: entity,id:'_id'}) }}'.replace('_id',$(this).val());
		}
	});

	{% if entity== 'match' %}
		$("#form_team optgroup[label!='"+$('#form_league option:selected').text()+"']").hide();
		
		$("#form_opponent option[value='"+$('#form_team').val()+"']").hide();
		if ($('#form_team').val()!=$('#form_opponent').val()) {
			$("#form_team option[value='"+$('#form_opponent').val()+"']").hide();
		}
		
		$("#form_opponent").on('change', function() {
			$("#form_team option").show();
			$("#form_team option[value='"+$('#form_opponent').val()+"']").hide();
		});
		$("#form_team").on('change', function() {
			$("#form_opponent option").show();
			$("#form_opponent option[value='"+$('#form_team').val()+"']").hide();
		});
		$("#form_league").on('change', function() {
			$("#form_team optgroup").show();
			$("#form_opponent optgroup").show();
			$("#form_team optgroup[label!='"+$('#form_league option:selected').text()+"']").hide();
			$("#form_opponent optgroup[label!='"+$('#form_league option:selected').text()+"']").hide();
		});
	{% endif %}
{% endblock %}

templates/flash_messages.html.twig
{% if messages.error is defined %}
{% for message in messages.error|reverse %}
<a class="hideMe" href="#"><div class=" flash-notice alert alert-danger text-center w-100">
<div class="animated delay-1s slow  alternate flash "><i class="fas fa-exclamation-circle"></i> {{message}} </div></div></a>
{% endfor %}
{% endif %}
{% if messages.warning is defined %}
{% for message in messages.warning|reverse %}
<a class="hideMe" href="#"><div class=" flash-notice alert alert-warning text-center w-100">
<div class="animated delay-1s slow  alternate flash "><i class="fas fa-exclamation-triangle"></i> {{message}} </div></div></a>
{% endfor %}
{% endif %}
{% if messages.success is defined %}
{% for message in messages.success|reverse %}
<a class="hideMe" href="#"><div class=" flash-notice alert alert-success text-center w-100">
<div class="animated delay-1s slow  alternate flash "><i class="fas fa-check"></i> {{message}} </div></div></a>
{% endfor %}
{% endif %}

templates/footer.html.twig
		<ul class="navbar-nav page-footer">
		  <li  class="bg-dark nav-item  text-center  pt-2 pb-0 ">
		  <blockquote class="blockquote">
  <p class="mb-0 text-secondary">{{appname}}  </p>
  <footer class="blockquote-footer">© 2019-2022 by <cite title="Source Title">
				<a href="#">Stefan Sander <i class="fa fa-envelope"> </i> </a>
			</cite></footer>
</blockquote>
			
		  </li>
		  </ul>

templates/layout.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

{% endblock %}

{% block css %}
<style>
	html, body {
	   margin: 0;
	   padding: 0;
	   height:100%;
	   background-color:#e9ecef;
		min-height: 100vh;
	}
	.fullheight {
	   height:100%;
	}
	.page-footer {
		bottom:0px;
		width:100%;
	}
	.bg-grey {
		background-color: #e9ecef;
	}
	.page-title {
		font-size:1.5em;
	 }
	 .navbar-expand {
		position:fixed;
		top:0px;
		width:100%;
		z-index:2000;
	 }	
.active i {
 color:#007bff ;
}
.active>a {
 color:#007bff!important ;
}
.dropdown-menu>.dropdown-item {
 background-color:#fff!important ;
}
.dropdown-menu>.dropdown-item:hover {
 background-color:#007bff!important ;
 color:#fff!important ;
}
.dropdown-menu>.active>a{
}
.shadow-inset {
	box-shadow: inset 0px 0px 15px #bbb;
}
.dropdown-menu>.active{
 color:#007bff!important ;
}
.skew {
 -webkit-transform:skew(10deg);
    -moz-transform:skew(10deg);
    -o-transform:skew(10deg);
    transform:skew(10deg);
}
</style>
{% endblock %}
{% block javascripts %}
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script>
	$(function() {
	{% block jquery %}
			$('.hideMe').click(function() {
				  $(this).animate({
					opacity: '0',
					},1000,function(){$(this).hide(500)})
				  });
	{% endblock %}
	});
	</script>
{% endblock %}

{% block body %}
{% block navigation %}
{% include 'navigation.html.twig' %}
{% endblock %}
	 <div id="page-container" class="p-4 bg-grey">
{% block banner %}
{% include 'banner.html.twig' %}
{% endblock %}
{% block content %}
	<ul class="list-group m-4 shadow-lg ">
	  <li class="list-group-item  bg-primary "><h2  class="text-center text-light page-title pt-1">{% block content_header %}{% endblock %}</h2></li>
	  <li class="list-group-item overflow-auto">
{% block flash_messages %}
{% include 'flash_messages.html.twig' %}
{% endblock %}
    {% block content_body %}hello world{% endblock %}
	</li>
	</ul>
{% endblock %}
	</div>
{% block footer %}
{% include 'footer.html.twig' %}
{% endblock %}
{% endblock %}

templates/navigation.html.twig
<nav class="navbar navbar-expand text-nowrap navbar-dark  bg-dark shadow">
  

    <ul class="navbar-nav w-100">
      <li class="nav-item  p-4">
        <a class="navbar-brand" href="{{path('index')}}" >{{appname}}</a>
		</a>
      </li>
      <li class="nav-item  p-4 {% if app.request.attributes.get('_route')=="scoreboard" %}active {%endif%} ">
        <a class="nav-link  " href="{{path('index')}}">
		<i class="fa fa-lg fa-list-ol mr-2"></i> scoreboard 
		</a>
      </li>
	  

{% if is_granted('ROLE_ADMIN') %} 


      <li class="nav-item p-4 dropdown {% if app.request.attributes.get('_route')=="edit_entity" or app.request.attributes.get('_route')=="add_entity" %}active {%endif%} ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class=" fa fa-lg fa-edit  mr-2"></i> entities 
        </a>
        <div class="dropdown-menu shadow " aria-labelledby="navbarDropdown">
		 {% for name,class in entities %}
			<a class="dropdown-item text-center p-3 {% if entity is defined and entity==name%}active{%endif%}" href="{{path('add_entity',{entity:name})}}">{{name}}</a>
		 {% endfor %}
        </div>
      </li>
	  
	  
	   {% endif %}
	   
	   
      <li class="nav-item w-100 float-right">
		<div class="p-4 float-right">
        <form class="" action="{{path('search_post')}}" method="POST">
		<input type="text" id="form_search" name="form[search]" required="required"  class="small pb-1" placeholder="search">
		
	  <button class="btn-sm btn btn-outline-secondary " type="submit">  Search <i class="fa fa-sm fa-search"></i></button>
    </form>
  </div>
      </li>
	   
      <li class="nav-item float-right pr-2">
		<div class="pt-4 float-right">
		<a class="btn-sm btn btn-outline-primary text-primary " href="{% if is_granted('ROLE_USER') %}{{path("app_logout")}}{% else %}{{path("app_login")}}{% endif %}"> {% if is_granted('ROLE_USER') %}Logout{% else %}Login{% endif %} <i class="fas fa-sign-in-alt"></i>
</a>
  </div>
      </li>
    </ul>
	
</nav>
<div style="height:100px;">
</div>

templates/scoreboard.html.twig
{% extends 'layout.html.twig' %}
{% block content_header %}scoreboard{% endblock %}
{% block content_body %}
<div class="table">
	<div class="row form-group">
		<div class="col-1">
			<label class="col-form-label">Liga</label>
		</div>
		<div class="col">
			<select class="form-control scoreboard_leagueSelector">
				{% for _league in leagues.findAll %}
					<option value="{{_league.id}}"{% if league.id==_league.id%} selected{%endif%}>{{_league.name}}</option>
				{% endfor %}
			</select>
		</div>
		<div class="w-100"></div>
	</div>
</div>
			<table class="table">
			  <thead>
				<tr>
				  <th scope="col" class="text-center">#</th>
				  <th scope="col">Mannschaft</th>
				  <th scope="col" class="text-center">Spiele</th>
				  <th scope="col" class="text-center">Siege</th>
				  <th scope="col" class="text-center">Unentschieden</th>
				  <th scope="col" class="text-center">Niederlagen</th>
				  <th scope="col" class="text-center">Tore</th>
				  <th scope="col" class="text-center">Gegentore</th>
				  <th scope="col" class="text-center">Punkte</th>
				</tr>
			  </thead>
			  <tbody>
			  {% set gameDay = null %}
				{% for team in teams %}
					{% if (gameDay is null)  or (gameDay > team.parties|length) %}
						{% set gameDay = team.parties|length %}
					{% endif %}

				<tr>
					<th scope="row" class="text-center">{{loop.index}}</th>
					<th scope="row"><a href="{{ path('edit_entity', {entity: 'team',id:team.id}) }}">{{team.name}}</a></th>
					<th scope="row" class="text-center">{{team.parties|length}}</th>
					<th scope="row" class="text-center">{{team.wins|length}}</th>
					<th scope="row" class="text-center">{{team.draws|length}}</th>
					<th scope="row" class="text-center">{{team.losses|length}}</th>
					<th scope="row" class="text-center">{{team.goals}}</th>
					<th scope="row" class="text-center">{{team.opponentGoals}}</th>
					<th scope="row" class="text-center">{{team.score}}</th>
				</tr>
				{% endfor %}
				{% if gameDay is null %}
					{% set gameDay = 0 %}
				{% endif %}
				<tr>
						<th colspan="9" class="text-right text-muted" >{{gameDay+1}}. Spieltag</th>
				</tr>
			  </tbody>
			</table>
				
{% endblock %}
{% block jquery %}
 {{ parent() }}
$('.scoreboard_leagueSelector').on('change', function() {
	if ($(this).val()=='null') {
	window.location = '{{ path('index') }}';
	} else {
	window.location = '{{ path('scoreboard',{leagueId:'_leagueId'}) }}'.replace('_leagueId',$(this).val());
	}
});
{% endblock %}

templates/search.html.twig
{% extends 'layout.html.twig' %}
{% block content_header %}search{% endblock %}
{% block content_body %}

<div class="accordion" id="accordionExample">
 <form name="searchForm" class=" w-100 pt-2 text-nowrap" action="{{path('search_post')}}" method="POST">
<div id="form" class="row">
<div class="col-sm-2">Results:</div>
<div class="col-sm-10">
{% if results|length==0 %}
no results
	{% endif %}
{% for key,result in results %}
  <div class="card">
    <div class="card-header  bg-secondary" id="headingOne">
        <button class="btn m-0 p-0  text-white btn-link" type="button" data-toggle="collapse" data-target="#collapse_{{key}}" aria-expanded="true" aria-controls="collapse_{{key}}">
         {{result|length}} results from {{key}}
        </button>
    </div>

    <div id="collapse_{{key}}" class="collapse" aria-labelledby="heading_{{key}}" data-parent="#accordionExample">

{% for k,entity in result %}
      <ul class="ul  border">
      <li><a href="{{path('edit_entity',{entity:key,id:entity.id})}}">{{entity}}</a></li></ul>
{% endfor %}
    </div>
  </div>
{% endfor %}    </div>
</div>
	</div>
	
	<div class="form-group row pt-2">
	<label class="col-form-label col-sm-2 required" for="form_league">Search:</label>
	<div class="col-sm-10 text-center"><input type="text" id="form_search" name="form[search]" required="required"  class="form-control "><button class="mt-2 btn btn-primary " type="submit">  Search <i class="fa  fa-search"></i></button></div>
    </div>
	</div>
    </form>
	
	
	
	

{% endblock %}